CREATE TABLE sales_channels (
    sales_channel_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    sales_channel_code VARCHAR(32) NOT NULL UNIQUE,
    sales_channel_name VARCHAR(100) NOT NULL,
    CONSTRAINT ck_sales_channels_code_non_blank CHECK (btrim(sales_channel_code) <> ''),
    CONSTRAINT ck_sales_channels_name_non_blank CHECK (btrim(sales_channel_name) <> '')
);

CREATE TABLE stores (
    store_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    store_code VARCHAR(50) NOT NULL UNIQUE,
    store_name VARCHAR(200) NOT NULL,
    country_code CHAR(2) NOT NULL,
    CONSTRAINT ck_stores_code_non_blank CHECK (btrim(store_code) <> ''),
    CONSTRAINT ck_stores_name_non_blank CHECK (btrim(store_name) <> ''),
    CONSTRAINT ck_stores_country_code CHECK (country_code ~ '^[A-Z]{2}$')
);

CREATE TABLE customers (
    customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY
);

CREATE TABLE product_categories (
    product_category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    category_code VARCHAR(50) NOT NULL UNIQUE,
    category_name VARCHAR(200) NOT NULL,
    CONSTRAINT ck_product_categories_code_non_blank CHECK (btrim(category_code) <> ''),
    CONSTRAINT ck_product_categories_name_non_blank CHECK (btrim(category_name) <> '')
);

CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    sku VARCHAR(100) NOT NULL UNIQUE,
    product_name VARCHAR(255) NOT NULL,
    product_category_id BIGINT NOT NULL REFERENCES product_categories(product_category_id),
    list_price NUMERIC(18,2) NULL,
    unit_cost NUMERIC(18,2) NULL,
    currency_code CHAR(3) NULL,
    CONSTRAINT ck_products_sku_non_blank CHECK (btrim(sku) <> ''),
    CONSTRAINT ck_products_name_non_blank CHECK (btrim(product_name) <> ''),
    CONSTRAINT ck_products_list_price_non_negative CHECK (
        list_price IS NULL OR list_price >= 0
    ),
    CONSTRAINT ck_products_unit_cost_non_negative CHECK (
        unit_cost IS NULL OR unit_cost >= 0
    ),
    CONSTRAINT ck_products_currency_code CHECK (
        currency_code IS NULL OR currency_code ~ '^[A-Z]{3}$'
    ),
    CONSTRAINT ck_products_currency_presence CHECK (
        (currency_code IS NOT NULL) = (list_price IS NOT NULL OR unit_cost IS NOT NULL)
    )
);

CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    sales_channel_id BIGINT NOT NULL REFERENCES sales_channels(sales_channel_id),
    store_id BIGINT NULL REFERENCES stores(store_id),
    customer_id BIGINT NULL REFERENCES customers(customer_id),
    order_timestamp TIMESTAMPTZ NOT NULL,
    currency_code CHAR(3) NOT NULL,
    order_amount NUMERIC(18,2) NULL,
    CONSTRAINT ck_orders_currency_code CHECK (currency_code ~ '^[A-Z]{3}$'),
    CONSTRAINT ck_orders_amount_non_negative CHECK (
        order_amount IS NULL OR order_amount >= 0
    )
);

CREATE TABLE order_items (
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    line_number INTEGER NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(product_id),
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(18,2) NOT NULL,
    discount_amount NUMERIC(18,2) NULL,
    line_amount NUMERIC(18,2) NOT NULL,
    CONSTRAINT uq_order_items_order_line UNIQUE (order_id, line_number),
    CONSTRAINT ck_order_items_line_number_positive CHECK (line_number > 0),
    CONSTRAINT ck_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT ck_order_items_unit_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT ck_order_items_discount_non_negative CHECK (
        discount_amount IS NULL OR discount_amount >= 0
    ),
    CONSTRAINT ck_order_items_line_amount_non_negative CHECK (line_amount >= 0)
);

CREATE TABLE payments (
    payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(order_id),
    payment_timestamp TIMESTAMPTZ NOT NULL,
    payment_status VARCHAR(50) NOT NULL,
    payment_amount NUMERIC(18,2) NOT NULL,
    CONSTRAINT ck_payments_status_non_blank CHECK (btrim(payment_status) <> ''),
    CONSTRAINT ck_payments_amount_non_negative CHECK (payment_amount >= 0)
);

CREATE TABLE returns (
    return_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_item_id BIGINT NOT NULL REFERENCES order_items(order_item_id),
    return_timestamp TIMESTAMPTZ NOT NULL,
    return_quantity INTEGER NOT NULL,
    return_amount NUMERIC(18,2) NULL,
    return_reason VARCHAR(255) NULL,
    CONSTRAINT ck_returns_quantity_positive CHECK (return_quantity > 0),
    CONSTRAINT ck_returns_amount_non_negative CHECK (
        return_amount IS NULL OR return_amount >= 0
    ),
    CONSTRAINT ck_returns_reason_non_blank CHECK (
        return_reason IS NULL OR btrim(return_reason) <> ''
    )
);
