CREATE TABLE pipeline_executions (
    pipeline_execution_id UUID NOT NULL PRIMARY KEY,
    predecessor_execution_id UUID NULL REFERENCES pipeline_executions(pipeline_execution_id),
    state VARCHAR(16) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    failure_category VARCHAR(64) NULL,
    failure_code VARCHAR(128) NULL,
    CONSTRAINT ck_pipeline_executions_state CHECK (
        state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'BLOCKED', 'FAILED')
    ),
    CONSTRAINT ck_pipeline_executions_predecessor_not_self CHECK (
        predecessor_execution_id IS NULL
        OR predecessor_execution_id <> pipeline_execution_id
    ),
    CONSTRAINT ck_pipeline_executions_started_at CHECK (
        started_at IS NULL OR started_at >= created_at
    ),
    CONSTRAINT ck_pipeline_executions_completed_at CHECK (
        completed_at IS NULL
        OR (started_at IS NOT NULL AND completed_at >= started_at)
    ),
    CONSTRAINT ck_pipeline_executions_failure_consistency CHECK (
        (state = 'FAILED' AND failure_category IS NOT NULL)
        OR (
            state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'BLOCKED')
            AND failure_category IS NULL
            AND failure_code IS NULL
        )
    ),
    CONSTRAINT ck_pipeline_executions_failure_code_category CHECK (
        failure_code IS NULL OR failure_category IS NOT NULL
    )
);

CREATE TABLE pipeline_stage_executions (
    pipeline_stage_execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    pipeline_execution_id UUID NOT NULL REFERENCES pipeline_executions(pipeline_execution_id),
    stage VARCHAR(32) NOT NULL,
    stage_sequence SMALLINT NOT NULL,
    state VARCHAR(16) NOT NULL,
    started_at TIMESTAMPTZ NULL,
    completed_at TIMESTAMPTZ NULL,
    failure_category VARCHAR(64) NULL,
    failure_code VARCHAR(128) NULL,
    CONSTRAINT ck_pipeline_stage_executions_stage_sequence CHECK (
        (stage = 'INGESTION' AND stage_sequence = 1)
        OR (stage = 'TRANSFORMATION' AND stage_sequence = 2)
        OR (stage = 'DATA_QUALITY' AND stage_sequence = 3)
    ),
    CONSTRAINT ck_pipeline_stage_executions_state CHECK (
        state IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'SKIPPED')
    ),
    CONSTRAINT uq_pipeline_stage_executions_pipeline_stage
        UNIQUE (pipeline_execution_id, stage),
    CONSTRAINT uq_pipeline_stage_executions_pipeline_sequence
        UNIQUE (pipeline_execution_id, stage_sequence),
    CONSTRAINT ck_pipeline_stage_executions_shape CHECK (
        (
            state = 'PENDING'
            AND started_at IS NULL
            AND completed_at IS NULL
            AND failure_category IS NULL
            AND failure_code IS NULL
        )
        OR (
            state = 'RUNNING'
            AND started_at IS NOT NULL
            AND completed_at IS NULL
            AND failure_category IS NULL
            AND failure_code IS NULL
        )
        OR (
            state = 'SUCCEEDED'
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND failure_category IS NULL
            AND failure_code IS NULL
        )
        OR (
            state = 'FAILED'
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND failure_category IS NOT NULL
        )
        OR (
            state = 'SKIPPED'
            AND started_at IS NULL
            AND completed_at IS NOT NULL
            AND failure_category IS NULL
            AND failure_code IS NULL
        )
    ),
    CONSTRAINT ck_pipeline_stage_executions_failure_code_category CHECK (
        failure_code IS NULL OR failure_category IS NOT NULL
    ),
    CONSTRAINT ck_pipeline_stage_executions_timestamp_order CHECK (
        started_at IS NULL
        OR completed_at IS NULL
        OR completed_at >= started_at
    )
);

CREATE INDEX ix_pipeline_executions_predecessor
ON pipeline_executions (predecessor_execution_id);
CREATE INDEX ix_pipeline_executions_state
ON pipeline_executions (state);
CREATE INDEX ix_pipeline_stage_executions_pipeline
ON pipeline_stage_executions (pipeline_execution_id);
